// Do not edit!  This file was autogenerated 
// by the "C:\Users\dababy\Desktop\gitclones\SRB2\comptime.bat" batch file 
// 
const char* compbranch = "Unknown"; 
const char* comprevision = "illegal"; 
